name: flutter_civix
description: Civix Flutter app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get_it: ^7.1.3
  rxdart: ^0.27.1
  intl: ^0.17.0
  equatable: ^2.0.2
  path_provider: ^2.0.2
  logger: ^1.0.0
  oktoast: ^3.0.0
  path: ^1.8.0
  built_value: ^8.0.6
  auto_route: ^2.2.0
  reactive_forms: ^10.4.1
  dartz: ^0.10.0-nullsafety.1

  connectivity: ^3.0.6
  dio: ^4.0.0

  provider: ^5.0.0
  flutter_bloc: ^7.0.0

  image_picker: ^0.7.5+2
  file_picker: ^3.0.2+2
  flutter_image_compress: ^1.0.0

  moor: ^4.3.2
  moor_db_viewer: ^4.0.0
  moor_flutter: ^4.0.0
  moor_generator: ^4.3.1
  sqflite: ^2.0.0+3
  sqlite3_flutter_libs: ^0.5.0

  share_plus: ^2.1.2
  shared_preferences: ^2.0.6

  animate_do: ^2.0.0

  google_fonts: ^2.1.0
  ansicolor: ^2.0.1
  awesome_dialog: ^2.1.0
  font_awesome_flutter: ^9.1.0
  eva_icons_flutter: ^3.0.0
  cupertino_icons: ^1.0.3
  carousel_slider: ^4.0.0-nullsafety.0
  flutter_svg: ^0.22.0
  animated_bottom_navigation_bar: ^0.3.2
  curved_navigation_bar: ^1.0.0

  url_launcher: ^6.0.8
  scroll_to_index: 2.0.0
  device_info: ^2.0.2
  device_preview: ^0.7.3
  uuid: ^3.0.4
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  json_serializable: ^4.1.3
  built_value_generator: ^8.0.6
  auto_route_generator: ^2.1.0
  flutter_gen_runner: ^3.1.1
  bloc_test: ^8.0.2
  freezed: ^0.14.2
  lint: 1.5.3

# Flutter Genrator For Assets
flutter_gen:
  output: lib/src/presentation/app/assets # Optional (default: lib/gen/)
  lineLength: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/jsons/general/
    - assets/jsons/civix/
    - assets/jsons/fgr/
    - assets/jsons/tsp/
    - assets/jsons/onbc/
    - assets/svgs/

flutter_intl:
  enabled: true
  arb_dir: assets/lang
  output_dir: lib/src/presentation/app/lang
